<?php

declare(strict_types=1);

namespace Cnx\LaravelTelegram\Facades;

use Cnx\LaravelTelegram\BotApiClient;
use Illuminate\Support\Facades\Facade;

/**
 * Telegram Bot API 10.2 facade.
 *
 * @method static \Cnx\LaravelTelegram\BotApiClient bot(?string $botConfigName = null)
 * @method static mixed execute(\Cnx\LaravelTelegram\BotApi\Request $request)
 * @method static mixed call(string $method, array<string, mixed> $parameters = [], string $returnType = 'Mixed')
 * @method static bool addStickerToSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AddStickerToSetRequest $request)
 * @method static bool answerCallbackQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerCallbackQueryRequest $request)
 * @method static bool answerChatJoinRequestQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerChatJoinRequestQueryRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\SentGuestMessage answerGuestQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerGuestQueryRequest $request)
 * @method static bool answerInlineQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerInlineQueryRequest $request)
 * @method static bool answerPreCheckoutQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerPreCheckoutQueryRequest $request)
 * @method static bool answerShippingQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerShippingQueryRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\SentWebAppMessage answerWebAppQuery(\Cnx\LaravelTelegram\BotApi\Generated\Requests\AnswerWebAppQueryRequest $request)
 * @method static bool approveChatJoinRequest(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ApproveChatJoinRequestRequest $request)
 * @method static bool approveSuggestedPost(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ApproveSuggestedPostRequest $request)
 * @method static bool banChatMember(\Cnx\LaravelTelegram\BotApi\Generated\Requests\BanChatMemberRequest $request)
 * @method static bool banChatSenderChat(\Cnx\LaravelTelegram\BotApi\Generated\Requests\BanChatSenderChatRequest $request)
 * @method static bool close()
 * @method static bool closeForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CloseForumTopicRequest $request)
 * @method static bool closeGeneralForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CloseGeneralForumTopicRequest $request)
 * @method static bool convertGiftToStars(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ConvertGiftToStarsRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\MessageId copyMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CopyMessageRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\MessageId> copyMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CopyMessagesRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatInviteLink createChatInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CreateChatInviteLinkRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatInviteLink createChatSubscriptionInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CreateChatSubscriptionInviteLinkRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ForumTopic createForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CreateForumTopicRequest $request)
 * @method static string createInvoiceLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CreateInvoiceLinkRequest $request)
 * @method static bool createNewStickerSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\CreateNewStickerSetRequest $request)
 * @method static bool declineChatJoinRequest(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeclineChatJoinRequestRequest $request)
 * @method static bool declineSuggestedPost(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeclineSuggestedPostRequest $request)
 * @method static bool deleteAllMessageReactions(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteAllMessageReactionsRequest $request)
 * @method static bool deleteBusinessMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteBusinessMessagesRequest $request)
 * @method static bool deleteChatPhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteChatPhotoRequest $request)
 * @method static bool deleteChatStickerSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteChatStickerSetRequest $request)
 * @method static bool deleteEphemeralMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteEphemeralMessageRequest $request)
 * @method static bool deleteForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteForumTopicRequest $request)
 * @method static bool deleteMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteMessageRequest $request)
 * @method static bool deleteMessageReaction(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteMessageReactionRequest $request)
 * @method static bool deleteMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteMessagesRequest $request)
 * @method static bool deleteMyCommands(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteMyCommandsRequest $request = null)
 * @method static bool deleteStickerFromSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteStickerFromSetRequest $request)
 * @method static bool deleteStickerSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteStickerSetRequest $request)
 * @method static bool deleteStory(\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteStoryRequest $request)
 * @method static bool deleteWebhook(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\DeleteWebhookRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatInviteLink editChatInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditChatInviteLinkRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatInviteLink editChatSubscriptionInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditChatSubscriptionInviteLinkRequest $request)
 * @method static bool editEphemeralMessageCaption(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditEphemeralMessageCaptionRequest $request)
 * @method static bool editEphemeralMessageMedia(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditEphemeralMessageMediaRequest $request)
 * @method static bool editEphemeralMessageReplyMarkup(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditEphemeralMessageReplyMarkupRequest $request)
 * @method static bool editEphemeralMessageText(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditEphemeralMessageTextRequest $request)
 * @method static bool editForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditForumTopicRequest $request)
 * @method static bool editGeneralForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditGeneralForumTopicRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool editMessageCaption(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageCaptionRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message editMessageChecklist(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageChecklistRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool editMessageLiveLocation(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageLiveLocationRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool editMessageMedia(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageMediaRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool editMessageReplyMarkup(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageReplyMarkupRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool editMessageText(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditMessageTextRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Story editStory(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditStoryRequest $request)
 * @method static bool editUserStarSubscription(\Cnx\LaravelTelegram\BotApi\Generated\Requests\EditUserStarSubscriptionRequest $request)
 * @method static string exportChatInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ExportChatInviteLinkRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message forwardMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ForwardMessageRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\MessageId> forwardMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ForwardMessagesRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Gifts getAvailableGifts()
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\OwnedGifts getBusinessAccountGifts(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetBusinessAccountGiftsRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\StarAmount getBusinessAccountStarBalance(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetBusinessAccountStarBalanceRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\BusinessConnection getBusinessConnection(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetBusinessConnectionRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatFullInfo getChat(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberOwner|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberAdministrator|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberMember|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberRestricted|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberLeft|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberBanned> getChatAdministrators(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatAdministratorsRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\OwnedGifts getChatGifts(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatGiftsRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberOwner|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberAdministrator|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberMember|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberRestricted|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberLeft|\Cnx\LaravelTelegram\BotApi\Generated\Types\ChatMemberBanned getChatMember(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatMemberRequest $request)
 * @method static int getChatMemberCount(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatMemberCountRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\MenuButtonCommands|\Cnx\LaravelTelegram\BotApi\Generated\Types\MenuButtonWebApp|\Cnx\LaravelTelegram\BotApi\Generated\Types\MenuButtonDefault getChatMenuButton(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetChatMenuButtonRequest $request = null)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\Sticker> getCustomEmojiStickers(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetCustomEmojiStickersRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\File getFile(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetFileRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\Sticker> getForumTopicIconStickers()
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\GameHighScore> getGameHighScores(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetGameHighScoresRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\BotAccessSettings getManagedBotAccessSettings(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetManagedBotAccessSettingsRequest $request)
 * @method static string getManagedBotToken(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetManagedBotTokenRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\User getMe()
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\BotCommand> getMyCommands(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetMyCommandsRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatAdministratorRights getMyDefaultAdministratorRights(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetMyDefaultAdministratorRightsRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\BotDescription getMyDescription(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetMyDescriptionRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\BotName getMyName(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetMyNameRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\BotShortDescription getMyShortDescription(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetMyShortDescriptionRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\StarAmount getMyStarBalance()
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\StarTransactions getStarTransactions(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetStarTransactionsRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\StickerSet getStickerSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetStickerSetRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\Update> getUpdates(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUpdatesRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\UserChatBoosts getUserChatBoosts(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUserChatBoostsRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\OwnedGifts getUserGifts(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUserGiftsRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\Message> getUserPersonalChatMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUserPersonalChatMessagesRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\UserProfileAudios getUserProfileAudios(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUserProfileAudiosRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\UserProfilePhotos getUserProfilePhotos(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GetUserProfilePhotosRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\WebhookInfo getWebhookInfo()
 * @method static bool giftPremiumSubscription(\Cnx\LaravelTelegram\BotApi\Generated\Requests\GiftPremiumSubscriptionRequest $request)
 * @method static bool hideGeneralForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\HideGeneralForumTopicRequest $request)
 * @method static bool leaveChat(\Cnx\LaravelTelegram\BotApi\Generated\Requests\LeaveChatRequest $request)
 * @method static bool logOut()
 * @method static bool pinChatMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\PinChatMessageRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Story postStory(\Cnx\LaravelTelegram\BotApi\Generated\Requests\PostStoryRequest $request)
 * @method static bool promoteChatMember(\Cnx\LaravelTelegram\BotApi\Generated\Requests\PromoteChatMemberRequest $request)
 * @method static bool readBusinessMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ReadBusinessMessageRequest $request)
 * @method static bool refundStarPayment(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RefundStarPaymentRequest $request)
 * @method static bool removeBusinessAccountProfilePhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RemoveBusinessAccountProfilePhotoRequest $request)
 * @method static bool removeChatVerification(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RemoveChatVerificationRequest $request)
 * @method static bool removeMyProfilePhoto()
 * @method static bool removeUserVerification(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RemoveUserVerificationRequest $request)
 * @method static bool reopenForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ReopenForumTopicRequest $request)
 * @method static bool reopenGeneralForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ReopenGeneralForumTopicRequest $request)
 * @method static string replaceManagedBotToken(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ReplaceManagedBotTokenRequest $request)
 * @method static bool replaceStickerInSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\ReplaceStickerInSetRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Story repostStory(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RepostStoryRequest $request)
 * @method static bool restrictChatMember(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RestrictChatMemberRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\ChatInviteLink revokeChatInviteLink(\Cnx\LaravelTelegram\BotApi\Generated\Requests\RevokeChatInviteLinkRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\PreparedInlineMessage savePreparedInlineMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SavePreparedInlineMessageRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\PreparedKeyboardButton savePreparedKeyboardButton(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SavePreparedKeyboardButtonRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendAnimation(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendAnimationRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendAudio(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendAudioRequest $request)
 * @method static bool sendChatAction(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendChatActionRequest $request)
 * @method static bool sendChatJoinRequestWebApp(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendChatJoinRequestWebAppRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendChecklist(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendChecklistRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendContact(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendContactRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendDice(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendDiceRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendDocument(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendDocumentRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendGame(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendGameRequest $request)
 * @method static bool sendGift(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendGiftRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendInvoice(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendInvoiceRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendLivePhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendLivePhotoRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendLocation(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendLocationRequest $request)
 * @method static list<\Cnx\LaravelTelegram\BotApi\Generated\Types\Message> sendMediaGroup(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendMediaGroupRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendMessageRequest $request)
 * @method static bool sendMessageDraft(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendMessageDraftRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendPaidMedia(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendPaidMediaRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendPhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendPhotoRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendPoll(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendPollRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendRichMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendRichMessageRequest $request)
 * @method static bool sendRichMessageDraft(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendRichMessageDraftRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendSticker(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendStickerRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendVenue(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendVenueRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendVideo(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendVideoRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendVideoNote(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendVideoNoteRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message sendVoice(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SendVoiceRequest $request)
 * @method static bool setBusinessAccountBio(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetBusinessAccountBioRequest $request)
 * @method static bool setBusinessAccountGiftSettings(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetBusinessAccountGiftSettingsRequest $request)
 * @method static bool setBusinessAccountName(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetBusinessAccountNameRequest $request)
 * @method static bool setBusinessAccountProfilePhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetBusinessAccountProfilePhotoRequest $request)
 * @method static bool setBusinessAccountUsername(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetBusinessAccountUsernameRequest $request)
 * @method static bool setChatAdministratorCustomTitle(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatAdministratorCustomTitleRequest $request)
 * @method static bool setChatDescription(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatDescriptionRequest $request)
 * @method static bool setChatMemberTag(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatMemberTagRequest $request)
 * @method static bool setChatMenuButton(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatMenuButtonRequest $request = null)
 * @method static bool setChatPermissions(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatPermissionsRequest $request)
 * @method static bool setChatPhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatPhotoRequest $request)
 * @method static bool setChatStickerSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatStickerSetRequest $request)
 * @method static bool setChatTitle(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetChatTitleRequest $request)
 * @method static bool setCustomEmojiStickerSetThumbnail(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetCustomEmojiStickerSetThumbnailRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool setGameScore(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetGameScoreRequest $request)
 * @method static bool setManagedBotAccessSettings(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetManagedBotAccessSettingsRequest $request)
 * @method static bool setMessageReaction(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMessageReactionRequest $request)
 * @method static bool setMyCommands(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyCommandsRequest $request)
 * @method static bool setMyDefaultAdministratorRights(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyDefaultAdministratorRightsRequest $request = null)
 * @method static bool setMyDescription(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyDescriptionRequest $request = null)
 * @method static bool setMyName(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyNameRequest $request = null)
 * @method static bool setMyProfilePhoto(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyProfilePhotoRequest $request)
 * @method static bool setMyShortDescription(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetMyShortDescriptionRequest $request = null)
 * @method static bool setPassportDataErrors(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetPassportDataErrorsRequest $request)
 * @method static bool setStickerEmojiList(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerEmojiListRequest $request)
 * @method static bool setStickerKeywords(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerKeywordsRequest $request)
 * @method static bool setStickerMaskPosition(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerMaskPositionRequest $request)
 * @method static bool setStickerPositionInSet(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerPositionInSetRequest $request)
 * @method static bool setStickerSetThumbnail(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerSetThumbnailRequest $request)
 * @method static bool setStickerSetTitle(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetStickerSetTitleRequest $request)
 * @method static bool setUserEmojiStatus(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetUserEmojiStatusRequest $request)
 * @method static bool setWebhook(\Cnx\LaravelTelegram\BotApi\Generated\Requests\SetWebhookRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Message|bool stopMessageLiveLocation(?\Cnx\LaravelTelegram\BotApi\Generated\Requests\StopMessageLiveLocationRequest $request = null)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\Poll stopPoll(\Cnx\LaravelTelegram\BotApi\Generated\Requests\StopPollRequest $request)
 * @method static bool transferBusinessAccountStars(\Cnx\LaravelTelegram\BotApi\Generated\Requests\TransferBusinessAccountStarsRequest $request)
 * @method static bool transferGift(\Cnx\LaravelTelegram\BotApi\Generated\Requests\TransferGiftRequest $request)
 * @method static bool unbanChatMember(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnbanChatMemberRequest $request)
 * @method static bool unbanChatSenderChat(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnbanChatSenderChatRequest $request)
 * @method static bool unhideGeneralForumTopic(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnhideGeneralForumTopicRequest $request)
 * @method static bool unpinAllChatMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnpinAllChatMessagesRequest $request)
 * @method static bool unpinAllForumTopicMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnpinAllForumTopicMessagesRequest $request)
 * @method static bool unpinAllGeneralForumTopicMessages(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnpinAllGeneralForumTopicMessagesRequest $request)
 * @method static bool unpinChatMessage(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UnpinChatMessageRequest $request)
 * @method static bool upgradeGift(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UpgradeGiftRequest $request)
 * @method static \Cnx\LaravelTelegram\BotApi\Generated\Types\File uploadStickerFile(\Cnx\LaravelTelegram\BotApi\Generated\Requests\UploadStickerFileRequest $request)
 * @method static bool verifyChat(\Cnx\LaravelTelegram\BotApi\Generated\Requests\VerifyChatRequest $request)
 * @method static bool verifyUser(\Cnx\LaravelTelegram\BotApi\Generated\Requests\VerifyUserRequest $request)
 *
 * @mixin BotApiClient
 *
 * @generated from Telegram Bot API 10.2
 */
final class BotApi extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return BotApiClient::class;
    }
}
